lr: 0.0005

train_num_epochs: 10000
train_batch_size: 16
train_num_samples: 4
train_max_num_points: 200

val_num_epochs: 200
val_batch_size: 4
val_num_samples: 50
val_max_num_points: 200

print_freq: 100
val_freq: 200
save_freq: 200

seed: 42
